#!/bin/bash

myArray=('*/#*#' '*/*~' '*/*pain_au_chocolat*' '*/*.o' '*/*.a' '*/*.so' '*/*.gcno' '*/*.gcda' '*/*.gcov' '#*#' '*~' '*pain_au_chocolat*' '*.o' '*.a' '*.so' '*.gcno' '*.gcda' '*.gcov')
EXECUTABLES="a.out"
IFS=','
read -a strarr <<< "$EXECUTABLES"
for name in "${strarr[@]}"; do
    file_count=$(find . -type f -perm 775 -name "$name" | wc -l)
    if [ "$file_count" -eq "1" ]; then
        echo 2
    fi
done