#!/bin/bash

myArray=('*/#*#' '*/*~' '*/*pain_au_chocolat*' '*/*.o' '*/*.a' '*/*.so' '*/*.gcno' '*/*.gcda' '*/*.gcov' '#*#' '*~' '*pain_au_chocolat*' '*.o' '*.a' '*.so' '*.gcno' '*.gcda' '*.gcov')

for str in ${myArray[@]}; do
    file_count=$(find "." -print | grep "$str" | wc -l)
    if [[ $file_count -gt 0 ]]; then
        echo $str
    fi
done

file_count=$(find "tmp" -type f -name "*" | wc -l)
if [[ $file_count -gt 0 ]]; then
    echo "pacoul"
fi