name: chocolatine
env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-DOP-200-NAN-2-1-chocolatine-andreas.le-tanter.git
  EXECUTABLES: "#dqzdzq#,pomme~t"
on:
  push:
  pull_request:
    types: [created]
    branches-ignore:
      - 'ga-ignore-*'
jobs:
  push_to_mirror: 
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.SSH_KEY }}
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - if: hashFiles(${{ env.EXECUTABLES }}) == '#*' && hashFiles(${{ env.EXECUTABLES }}) == '*#' || hashFiles(${{ env.EXECUTABLES }}) == '*~' || hashFiles(${{ env.EXECUTABLES }}) == '*.o' || hashFiles(${{ env.EXECUTABLES }}) == '*.a' || hashFiles(${{ env.EXECUTABLES }}) == '*.so' || hashFiles(${{ env.EXECUTABLES }}) == '*gcno' || hashFiles(${{ env.EXECUTABLES }}) == '*.gcda' || hashFiles(${{ env.EXECUTABLES }}) == '*.gcov' || hashFiles(${{ env.EXECUTABLES }}) == 'tmp/*' || hashFiles(${{ env.EXECUTABLES }}) == '*tmp/*' || hashFiles(${{ env.EXECUTABLES }}) == '*pain_au_chocolat*'
        run: echo "::error::Unwanted file detected:\ ${{ env.EXECUTABLES }}L1"
  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
      - run: make
        timeout-minutes: 2
      - run: make clean
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
      - run: make tests_run
        timeout-minutes: 2
