name: chocolatine
env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-DOP-200-NAN-2-1-chocolatine-andreas.le-tanter.git
  EXECUTABLES:
on:
  push:
  pull_request:
    types: [created]
    branches-ignore:
      - 'ga-ignore-*'
jobs:
  push_to_mirror: 
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.SSH_KEY }}
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          myArray=('#*#' '*~' '*pain_au_chocolat*' '*.o' '*.a' '*.so' '*.gcno' '*.gcda' '*.gcov')
          find=0
          for str in ${myArray[@]}; do
              file_count=$(find -type f -name "$str" | wc -l)
              if [[ $file_count -gt 0 ]]; then
                  echo "::error title="Unwanted file detected: $str#L1"::$str"
                  find=1
              fi
          done
          if [ "$find" -eq "1" ]; then
            exit 2
          fi
  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
      - run: make
        timeout-minutes: 2
      - run: make clean
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
      - run: make tests_run
        timeout-minutes: 2
