name: GitHub Actions Mirroring
on: [push, pull]
  issue_comment:
    types: [created, deleted]
jobs:
  to_github:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          git@github.com:EpitechPromo2026/B-DOP-200-NAN-2-1-bschocolatine-andreas.le-tanter.git
        ssh_private_key:
          ${{ secrets.SSH_KEY }}