name: GitHub Actions Mirroring
env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-DOP-200-NAN-2-1-chocolatine-andreas.le-tanter.git
  EXECUTABLES:
on:
  push:
  pull_request:
    types: [created]
    branches-ignore:    
      - 'ga-ignore-*'
jobs:
  to_github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.SSH_KEY }}
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
      - run: ls
  check_program_compilation:
    runs-on: ubuntu-latest
    steps: timeout-minutes: 2
      - run: make
    steps:
      -run: make clean